### ISSUE TITLE
`@lumino/coreutils` is hard pinned

### ISSUE THREAD

**Issue by trungleduc** [QuantStack/jupydrive-s3#24]
Is there any reason `@lumino/coreutils` is fixed to 2.1.2? 

https://github.com/QuantStack/jupydrive-s3/blob/a8574a3fe28338502a4cea5b7c1cc6bfebd76a6b/package.json#L65

**Comment by DenisaCG** [comment]
As far as I'm aware there isn't any reason for it to be pinned. The package was added in the PR integrating the auth plugin, @afshin was this intentional?
